version: '3'

services:  
  mongodb:
    image: mongo
    ports:
        - 27017:27017
  kafka:
    image: landoop/fast-data-dev:latest
    ports:
        - 3030:3030
        - 9092:9092
    environment:
      - ADV_HOST=10.0.75.1
